### PR TITLE
remove string_types

### LINKED ISSUE #37: AttributeError: module 'mkdocs.utils' has no attribute 'string_types' on mkdocs build
**Describe the bug**
I followed the instructions and created docs. My folder structure looks like this: 

work_docs\
     docs\
       index.md
       tring.md
     site\
     mkdocs.yml

when I try to do mkdocs build it throws the error: AttributeError: module 'mkdocs.utils' has no attribute 'string_types' on mkdocs build

**To Reproduce**
mkdocs.yml: 
```
site_name: My Docs
theme: 'material'
edit_uri: ''
plugins:
  - search
  # - mkdocs-versioning:
  #     version: 1.0.0

nav:
  - Home: 'index.md'
  - Files: 'tring.md'
  - Version: '../'

```
The site build properly when I comment the lines: 

 `- mkdocs-versioning:
         version: 1.0.0
`

But I cannot see the folder structure like https://github.com/zayd62/mkdocs-versioning-test

I am not using gh-pages or git. This is just static site. 

Pip Freeze:
Markdown==3.2.1
mkdocs==1.1
Python==3.7.4
mkdocs-versioning==0.1.0

Any help will be appreciated. Thanks

### PR DESCRIPTION
**Pull request by timvink**
Fixes https://github.com/zayd62/mkdocs-versioning/issues/37

### CODE REVIEW

**Comment by zayd62** [comment]
Hi @timvink Thanks for pull request, see #40

**Comment by zayd62** [comment]
hey @timvink merged your changes, updated mkdocs dependencies. plugin is working on my end. before i upload to pypi, I was hoping you could check it out and see if it is working on your end. its on a branch called ` string_types_fix`

**Comment by timvink** [comment]
Yup, works here!

**Comment by zayd62** [comment]
great. will upload to pypi. Also, I added you as a contributor

**Comment by timvink** [comment]
Thanks. 

> Also, I added you as a contributor. 

I'll make sure to address any bug fixes needed to keep the plugin working & when you are not available. Let's see it as a backup --> I'll make sure all changes are approved by you first.

**Pull request merged**
