### PR TITLE
capture OSX PermissionError when deleting folders

### LINKED ISSUE #32: Failed building for the second try
I'm following your guide in #21. When I run `mkdocs build`, I got the `site` directory as follows:

```
404.html       assets         search         sitemap.xml.gz
RC3 1.0.0      index.html     sitemap.xml
```

I then run `mkdocs gh-deploy`, but got a different [site](https://amber1990zhang.github.io/doc-115/) from expectation. There is no version selector and the `version` in the nav is 404.

Then I tried to build for the second time. The returned messages are:

```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/bin/mkdocs", line 10, in <module>
    sys.exit(cli())
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/mkdocs/__main__.py", line 163, in build_command
    ), dirty=not clean)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/mkdocs/commands/build.py", line 298, in build
    config['plugins'].run_event('post_build', config)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/mkdocs/plugins.py", line 94, in run_event
    result = method(item, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/mkversion/entry.py", line 45, in on_post_build
    version(config, self.config)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/mkversion/version.py", line 47, in version
    os.remove(f.path)
PermissionError: [Errno 1] Operation not permitted: '/Users/zhangying/Desktop/doc-115/site/search'
```
I tried with both python3 and the virtual environment but the same error happens.
You can find my project [here](https://github.com/Amber1990Zhang/doc-115).

### PR DESCRIPTION
**Pull request by ppanero**
Closes https://github.com/zayd62/mkdocs-versioning/issues/32

### CODE REVIEW

**Comment by timvink** [comment]
Just one comment from my side. Why not just always use `shutil.rmtree(f.path)`? It works across all platforms

**Comment by zayd62** [comment]
`os.remove()` deletes files only and recommends `os.rmdir()` to remove directories
`os.rmdir()` removes directories but recommends `shutil.rmtree()`
 `shutil.rmtree()` removes directories but cant remove individual files.
individual files and folders need to be removed

**Comment by ppanero** [comment]
Thanks for the merge! @zayd62 

@timvink As @zayd62 mention `rmtree`does not work for files. However, we can refactor the code to remove files with `remove` and directories with `rmtree`. Is this something that would be useful? Im willing to contribute on it.

**Comment by zayd62** [comment]
so **current way** is for each file:
- apply `os.remove()` --> catch `IsADirectoryError` --> apply `shutill.rmtree()`

**proposed solution** is for each file:
- detected if file or folder --> if folder, apply `shutill.rmtree()` else apply `os.remove()`

so here is the current code with @ppanero changes

```python
    # clean up old files. need to do manually so that built docs are kept but
    # built docs are in folders
    item_to_delete = ['assets', 'search']
    with os.scandir(built_docs_path) as files:
        for f in files:
            if not f.is_dir() or (f.name in item_to_delete):
                try:
                    os.remove(f.path)
                # PermissionError happens in OSX see:
                # https://github.com/zayd62/mkdocs-versioning/issues/32
                except (IsADirectoryError, PermissionError):
                    shutil.rmtree(f.path)
```

to something like
```python
    # clean up old files. need to do manually so that built docs are kept but
    # built docs are in folders
    item_to_delete = ['assets', 'search']
    with os.scandir(built_docs_path) as files:
        for f in files:
            if not f.is_dir() or (f.name in item_to_delete):
                if f.is_dir():
                    shutil.rmtree(f.path)
                else:
                    os.remove(f.path)    
            
```

**Comment by ppanero** [comment]
I think the `f.is_dir()`is redundant then. What about:

``` python
# clean up old files. need to do manually so that built docs are kept but
    # built docs are in folders
    item_to_delete = ['assets', 'search']
    with os.scandir(built_docs_path) as files:
        for f in files:
            if not f.is_dir():
                    os.remove(f.path)
            elif f.name in item_to_delete:
                    shutil.rmtree(f.path)
```

**Comment by zayd62** [comment]
yep. working on my end. I was going to upload to pypi before you came in. Ill commit your suggestion, upload to pypi. should be uploaded within the hour.

**Comment by ppanero** [comment]
Thanks! For future reference when contributing. I am a bit confused on the branchin/merges.

- Why are commits not rebased? This might just be my personal OCD, but commit trees look much cleaner :)

- Shall I do PRs to branches instead of master? Doesn´t this generates much more "merge" commits? and a less maintainable tree?

Probably this questions are not suitable for an issue. Do you have a gitter/IRC/etc. channel where we can discuss this things (and future PRs). Most likely we are gonna use this in many projects plus our documentation service. Thanks!

**Comment by zayd62** [comment]
I want my master branch to act as "ready for the public". i.e. whatever happens either to the code or the repository itself, I want to be able to checkout the master branch and know i have working code. that why the master branch has very few commits to them and pretty much all of them are merging pull requests and a lot of them are tagged as well to signify a "production release", usually semver numbers 

I try use branches as a place to experiment, failed experiments means deleted branches, successful experiments either stay or get merged into master if it becomes a new feature. I did delete a bunch of branches github said was stale recently.

I like to visualise things and the network graph https://github.com/zayd62/mkdocs-versioning/network. combined with this plugin https://github.com/mhutchie/vscode-git-graph means I can visualise the different branches and how it merges and divergers from other branches quite nicely in my opinion. 

sure maybe i could learn rebasing but it not a very active project nor do i see it becoming a very active project simply.

# activity

to be perfectly honest, I very rarely touch this project. largest gap between commits was 5 oct 2019 and this march when, at some point, mkdocs changed the plugin api and this mac os specific issue right here which i can do nothing about as i dont have a mac. 

the only reason I see this project needing updating is if `mkdocs` or `pyyaml`, two external dependencies gets updated. maybe dependabot could somehow update dependencies and run the tests. if tests past with updated dependencies then nothing needs to done. if the tests fail, then we step in, fix the bug, update dependencies and issue a new upload to pypi.

A lot of how this project works is based on infering what already exists and acting on those inferences. thats why mkdocs complains about relative links. its very "passive", a simply config change and the rest is done. although there are some nuances such as the fact that mkdocs deploy just does not work (for a reason I have forgotten) so you have to use the deploy function that I wrote and you may need to "sync" your docs

Also, Im a final year computer science student. time spent on this means less time spent on my final year thesis and coursework. this was built as a summer project and who knows, maybe this summer ill be able to start closing some of these issues


# new version

any ways, new version **0.2.1** is on pypi. check it out

**Comment by timvink** [comment]
Thanks @zayd62 and @ppanero !

**Pull request merged**
